# Generated by Django 5.0.3 on 2024-06-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='diasCierreLicitacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
