# Generated by Django 5.0.3 on 2024-05-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preguntasbbdd_licitacion_archivolicitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasbbdd',
            name='idPreguntas',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de pregunta'),
        ),
    ]
