# Generated by Django 5.0.4 on 2024-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='archivolicitacion',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
