# Generated by Django 5.0.3 on 2024-05-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_preguntasbbdd_idpreguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='archivoLicitacion',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Archivo de la licitación'),
        ),
    ]
