# Generated by Django 5.0.4 on 2024-04-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_archivolicitacion_licitacion_archivolicitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='archivoLicitacion',
            field=models.FileField(blank=True, null=True, upload_to='Licibot_module/Licibot/media/'),
        ),
    ]
