# Generated by Django 5.0.3 on 2024-05-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_licitacion_archivolicitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='descripcionLicitacion',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descripción de la licitación'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='idLicitacion',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Id de licitación'),
        ),
    ]
