# Generated by Django 5.0.3 on 2024-05-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_licitacion_descripcionlicitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='archivoLicitacion',
            field=models.FileField(blank=True, null=True, upload_to='licitaciones/%Y/%m/%d/', verbose_name='Archivo de la licitación'),
        ),
    ]
