# Generated by Django 5.0.4 on 2024-04-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntasbbdd',
            fields=[
                ('idPreguntas', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de preguntas')),
                ('nombrePregunta', models.CharField(max_length=80, verbose_name='Texto de la pregunta')),
            ],
        ),
    ]
