# Generated by Django 5.0.4 on 2024-04-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preguntasbbdd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasbbdd',
            name='idPreguntas',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de pregunta'),
        ),
    ]
